[build]
  publish = "."

[[redirects]]
  from = "/*.sql"
  to = "/index.html"
  status = 404
  force = true

[[redirects]]
  from = "/database/*"
  to = "/index.html"
  status = 404
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
